---
# if Firewall rules to route all traffic through the Achor IPi
# then you need to drop the IPTABLES before being able to retrieve the anchor IP
- name: Retrieve DO Droplet Anchor IP
  uri:
    url: "{{digital_ocean_metadata_anchor_ipv4_url}}"
    body_format: raw
    method: GET
    follow_redirects: all
    return_content: yes
    timeout: 3
    status_code: 200,-1
    timeout: 60
  register: do_droplet_anchor_ip
  when: floating_ip_is_assigned_to_this_droplet
  retries: 3
  ignore_errors: true

...
